#pragma once
#include "../tracks/SpatialIndex.hpp"
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/classes/engine.hpp>
#include <godot_cpp/classes/object.hpp>
#include <godot_cpp/templates/hash_map.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/rid.hpp>
#include <godot_cpp/variant/vector3.hpp>

namespace godot {
    /* The electrical topology of the overhead traction wires - kept apart from the rendering of
     * them, the same split TrackManager has against the track rendering. Ports
     * Traction.cpp/TractionPower.cpp of the original engine: named power sources feeding wire
     * spans, a resistive network built once per scenery load
     * (traction_table::InitTraction()), and the geometric "which wire is above this point" query
     * (scene::basic_cell::update_traction()).
     *
     * Not ported: TTraction::PowerSet()'s section-marker replacement (Traction.cpp:747-806, only
     * relevant when a sectioning cabin sits between two differently named substations) and
     * update_traction()'s pantograph-horn lateral tolerance. Both are refinements on top of the
     * network and contact logic ported here, not needed for a wire to deliver the right voltage. */
    class TractionPowerServer : public Object {
            GDCLASS(TractionPowerServer, Object)

        public:
            static TractionPowerServer *get_instance() {
                return Object::cast_to<TractionPowerServer>(
                        Engine::get_singleton()->get_singleton("TractionPowerServer"));
            }

        private:
            static void _bind_methods();

            /* Original engine: Traction.cpp's own "close enough to be one continuous wire"
             * distance, used both for the connectivity graph and for the tolerance at a span's
             * ends in the contact test. */
            static constexpr double ENDPOINT_EPSILON = 0.25;
            static constexpr double GRID_CELL_SIZE = 500.0;
            static constexpr double QUERY_MARGIN = 10.0;

            /// Mirrors TTractionPowerSource's own members.
            struct PowerSource {
                    String name;
                    double nominal_voltage = 0.0;
                    double voltage_frequency = 0.0;
                    double internal_resistance = 0.2;
                    double max_output_current = 0.0;
                    double fast_fuse_timeout = 1.0;
                    int fast_fuse_repetition = 3;
                    double slow_fuse_timeout = 60.0;
                    bool recuperation = false;
                    bool is_autogenerated = false;

                    double total_current = 0.0;
                    double total_admittance = 1e-10;
                    double total_previous_admittance = 1e-10;
                    double output_voltage = 0.0;
                    bool fast_fuse = false;
                    bool slow_fuse = false;
                    double fuse_timer = 0.0;
                    int fuse_counter = 0;
                    /// Whether any load asked for current since the last tick - see tick().
                    bool loaded = false;

                    bool fuse() const {
                        return fast_fuse || slow_fuse;
                    }
                    /// Port of TTractionPowerSource::Update(dt).
                    void tick(double p_delta);
                    /// Port of TTractionPowerSource::CurrentGet(res).
                    double current_get(double p_resistance);
            };

            struct Wire {
                    Vector3 p1;
                    Vector3 p2;
                    String power_supply_name;
                    double nominal_voltage = 0.0;
                    double max_current = 0.0;
                    double resistivity = 0.0;

                    /// psPowered - a directly powered (short-circuit) wire.
                    RID power_source;
                    RID power_near[2];   // psPower
                    double resistance[2] = {-1.0, -1.0}; // fResistance
                    RID next[2];         // hvNext
                    int next_endpoint[2] = {-1, -1};     // iNext

                    double length() const {
                        return p1.distance_to(p2);
                    }
            };

            HashMap<RID, PowerSource> power_sources;
            HashMap<String, RID> power_sources_by_name;
            int64_t next_power_source_id = 0;
            HashMap<RID, Wire> wires;
            int64_t next_wire_id = 0;
            Ref<SpatialIndex> spatial_index;

            void _on_process_frame();
            void _resolve_power_sources();
            void _connect_wires();
            void _propagate_resistance();
            void _resistance_walk(const RID &p_from_wire, int p_direction, double p_resistance, const RID &p_source);
            /* Height of one wire above a point along the pantograph's plane; INF when the plane
             * misses the span, or the wire is below the point or outside the collector width
             * (scene::basic_cell::update_traction()'s geometry test). */
            double _wire_height_above(
                    const Wire &p_wire, const Vector3 &p_position, const Vector3 &p_up, const Vector3 &p_forward,
                    const Vector3 &p_left, double p_width) const;

        public:
            TractionPowerServer();
            ~TractionPowerServer() override;

            RID power_source_create();
            void power_source_set_params(
                    const RID &p_power_source, const String &p_name, double p_nominal_voltage,
                    double p_voltage_frequency, double p_internal_resistance, double p_max_output_current,
                    double p_fast_fuse_timeout, int p_fast_fuse_repetition, double p_slow_fuse_timeout,
                    bool p_recuperation, bool p_is_autogenerated);
            RID power_source_get_rid_by_name(const String &p_name) const;
            void power_source_free(const RID &p_power_source);

            RID wire_create();
            void wire_set_params(
                    const RID &p_wire, const Vector3 &p_p1, const Vector3 &p_p2, const String &p_power_supply_name,
                    double p_nominal_voltage, double p_max_current, double p_resistivity);
            void wire_free(const RID &p_wire);

            /* Resolves named power sources (auto-creating one from a wire's own nominal values
             * when the name matches none - traction_table::InitTraction()'s fallback,
             * Traction.cpp:704-721), connects wire endpoints into a network and propagates
             * source and resistance outward from every directly powered wire. Called once per
             * scenery load, after every wire and source of that load exists. */
            void network_build();

            /* Port of TTraction::VoltageGet(u, i). `p_assumed_voltage` is the vehicle's own
             * previous reading, used only to derive an equivalent load resistance - the same
             * relaxation the original uses - and `p_current` the instantaneous draw. */
            double wire_get_voltage(const RID &p_wire, double p_assumed_voltage, double p_current);

            /// Which wire span passes above a point within the collector's width, or an invalid RID.
            RID wire_find_above(
                    const Vector3 &p_position, const Vector3 &p_up, const Vector3 &p_forward, const Vector3 &p_left,
                    double p_width) const;
            /* The same query with the wire's height, as {rid, height}. `height` is INF when no
             * wire is found - the original's own "no wire in reach" (scene.cpp resets
             * PantTraction to DBL_MAX before every scan), which the raise simulation relies on to
             * keep extending the pantograph to its joint limit. */
            Dictionary wire_find_above_with_height(
                    const Vector3 &p_position, const Vector3 &p_up, const Vector3 &p_forward, const Vector3 &p_left,
                    double p_width) const;
            /* The height of an already found wire, recomputed every frame like the original does
             * for the pantograph's current wire (DynObj.cpp:8255-8284) - INF once the pantograph
             * has left the span, which calls for a new search. */
            double wire_get_height_above(
                    const RID &p_wire, const Vector3 &p_position, const Vector3 &p_up, const Vector3 &p_forward,
                    const Vector3 &p_left, double p_width) const;
    };
} // namespace godot
