#include "TractionPowerServer.hpp"
#include <godot_cpp/classes/scene_tree.hpp>
#include <godot_cpp/classes/window.hpp>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

namespace godot {
    void TractionPowerServer::_bind_methods() {
        ClassDB::bind_method(D_METHOD("power_source_create"), &TractionPowerServer::power_source_create);
        ClassDB::bind_method(
                D_METHOD(
                        "power_source_set_params", "power_source", "name", "nominal_voltage", "voltage_frequency",
                        "internal_resistance", "max_output_current", "fast_fuse_timeout", "fast_fuse_repetition",
                        "slow_fuse_timeout", "recuperation", "is_autogenerated"),
                &TractionPowerServer::power_source_set_params, DEFVAL(false));
        ClassDB::bind_method(
                D_METHOD("power_source_get_rid_by_name", "name"), &TractionPowerServer::power_source_get_rid_by_name);
        ClassDB::bind_method(D_METHOD("power_source_free", "power_source"), &TractionPowerServer::power_source_free);

        ClassDB::bind_method(D_METHOD("wire_create"), &TractionPowerServer::wire_create);
        ClassDB::bind_method(
                D_METHOD(
                        "wire_set_params", "wire", "p1", "p2", "power_supply_name", "nominal_voltage", "max_current",
                        "resistivity"),
                &TractionPowerServer::wire_set_params);
        ClassDB::bind_method(D_METHOD("wire_free", "wire"), &TractionPowerServer::wire_free);
        ClassDB::bind_method(D_METHOD("network_build"), &TractionPowerServer::network_build);

        ClassDB::bind_method(
                D_METHOD("wire_get_voltage", "wire", "assumed_voltage", "current"),
                &TractionPowerServer::wire_get_voltage);
        ClassDB::bind_method(
                D_METHOD("wire_find_above_with_height", "position", "up", "forward", "left", "width", "horn_width"),
                &TractionPowerServer::wire_find_above_with_height);
        ClassDB::bind_method(
                D_METHOD(
                        "wire_follow_above", "from_wire", "position", "up", "forward", "left", "width",
                        "horn_width"),
                &TractionPowerServer::wire_follow_above);
    }

    TractionPowerServer::TractionPowerServer() {
        spatial_index.instantiate();
        spatial_index->set_cell_size(GRID_CELL_SIZE);
        if (SceneTree *tree = Object::cast_to<SceneTree>(Engine::get_singleton()->get_main_loop());
            tree != nullptr) {
            tree->connect("process_frame", callable_mp(this, &TractionPowerServer::_on_process_frame));
        }
    }

    TractionPowerServer::~TractionPowerServer() {
        if (SceneTree *tree = Object::cast_to<SceneTree>(Engine::get_singleton()->get_main_loop());
            tree != nullptr) {
            tree->disconnect("process_frame", callable_mp(this, &TractionPowerServer::_on_process_frame));
        }
    }

    /* The sources are ticked from the frame, the way the original ticks them from its own
     * simulation step - see the quirk PowerSource::tick() documents about loads asking on a
     * different beat. */
    void TractionPowerServer::_on_process_frame() {
        if (Engine::get_singleton()->is_editor_hint()) {
            return;
        }
        const double delta = Engine::get_singleton()->get_main_loop() != nullptr
                                     ? Object::cast_to<SceneTree>(Engine::get_singleton()->get_main_loop())
                                               ->get_root()
                                               ->get_process_delta_time()
                                     : 0.0;
        for (KeyValue<RID, PowerSource> &entry: power_sources) {
            entry.value.tick(delta);
        }
    }

    void TractionPowerServer::PowerSource::tick(const double p_delta) {
        if (fast_fuse || slow_fuse) {
            total_current = 0.0;
        }
        if (total_current > max_output_current) {
            fast_fuse = true;
            fuse_counter += 1;
            if (fuse_counter > fast_fuse_repetition) {
                slow_fuse = true;
                UtilityFunctions::push_warning(
                        vformat("Power overload: \"%s\" disabled for %ss", name, slow_fuse_timeout));
            } else {
                UtilityFunctions::push_warning(
                        vformat("Power overload: \"%s\" disabled for %ss", name, fast_fuse_timeout));
            }
            fuse_timer = 0.0;
        }
        if (fast_fuse || slow_fuse) {
            total_admittance = 0.0;
            fuse_timer += p_delta;
            if (!slow_fuse) {
                if (fuse_timer > fast_fuse_timeout) {
                    fast_fuse = false;
                }
            } else if (fuse_timer > slow_fuse_timeout) {
                slow_fuse = false;
                fuse_counter = 0;
            }
        }
        /* Quirk: the original updates the sources and asks them for current inside one simulation
         * step; here the loads ask from render frames while the sources tick on their own, so a
         * hitching frame runs a tick with nobody asking - keep the previous load then instead of
         * dropping it to nothing, which made the next current_get() return 0 V and trip
         * NoVoltRelay. */
        if (!loaded && !fast_fuse && !slow_fuse) {
            return;
        }
        loaded = false;
        total_previous_admittance = total_admittance;
        if (Math::is_zero_approx(total_previous_admittance)) {
            total_previous_admittance = 1e-10;
        }
        total_admittance = 1e-10;
    }

    double TractionPowerServer::PowerSource::current_get(const double p_resistance) {
        if (fast_fuse || slow_fuse) {
            if (p_resistance < 100.0) {
                fuse_timer = 0.0;
            }
            return 0.0;
        }
        if (!Math::is_zero_approx(p_resistance)) {
            total_admittance += 1.0 / p_resistance;
        }
        loaded = true;
        const double nominal = total_previous_admittance < 0.0 ? nominal_voltage * 1.083 : nominal_voltage;
        /* An exact comparison like the original's TotalPreviousAdmitance != 0.0 - the 1e-10 floor
         * tick() sets is within is_zero_approx()'s tolerance, and treating it as zero made every
         * such query return no current. */
        total_current = total_previous_admittance != 0.0
                                ? nominal / (internal_resistance + (1.0 / total_previous_admittance))
                                : 0.0;
        output_voltage = nominal - (internal_resistance * total_current);
        return total_current / (p_resistance * total_previous_admittance);
    }

    RID TractionPowerServer::power_source_create() {
        next_power_source_id += 1;
        const RID rid = UtilityFunctions::rid_from_int64(next_power_source_id);
        power_sources.insert(rid, PowerSource());
        return rid;
    }

    void TractionPowerServer::power_source_set_params(
            const RID &p_power_source, const String &p_name, const double p_nominal_voltage,
            const double p_voltage_frequency, const double p_internal_resistance, const double p_max_output_current,
            const double p_fast_fuse_timeout, const int p_fast_fuse_repetition, const double p_slow_fuse_timeout,
            const bool p_recuperation, const bool p_is_autogenerated) {
        PowerSource *source = power_sources.getptr(p_power_source);
        if (source == nullptr) {
            return;
        }
        source->name = p_name;
        source->nominal_voltage = p_nominal_voltage;
        source->voltage_frequency = p_voltage_frequency;
        source->internal_resistance = p_internal_resistance;
        source->max_output_current = p_max_output_current;
        source->fast_fuse_timeout = p_fast_fuse_timeout;
        source->fast_fuse_repetition = p_fast_fuse_repetition;
        source->slow_fuse_timeout = p_slow_fuse_timeout;
        source->recuperation = p_recuperation;
        source->is_autogenerated = p_is_autogenerated;
        if (!p_name.is_empty()) {
            power_sources_by_name.insert(p_name, p_power_source);
        }
    }

    RID TractionPowerServer::power_source_get_rid_by_name(const String &p_name) const {
        const RID *rid = power_sources_by_name.getptr(p_name);
        return rid != nullptr ? *rid : RID();
    }

    void TractionPowerServer::power_source_free(const RID &p_power_source) {
        const PowerSource *source = power_sources.getptr(p_power_source);
        if (source != nullptr) {
            const RID *named = power_sources_by_name.getptr(source->name);
            if (named != nullptr && *named == p_power_source) {
                power_sources_by_name.erase(source->name);
            }
        }
        power_sources.erase(p_power_source);
    }

    RID TractionPowerServer::wire_create() {
        next_wire_id += 1;
        const RID rid = UtilityFunctions::rid_from_int64(next_wire_id);
        wires.insert(rid, Wire());
        return rid;
    }

    void TractionPowerServer::wire_set_params(
            const RID &p_wire, const Vector3 &p_p1, const Vector3 &p_p2, const String &p_power_supply_name,
            const double p_nominal_voltage, const double p_max_current, const double p_resistivity) {
        Wire *wire = wires.getptr(p_wire);
        if (wire == nullptr) {
            return;
        }
        wire->p1 = p_p1;
        wire->p2 = p_p2;
        wire->power_supply_name = p_power_supply_name;
        wire->nominal_voltage = p_nominal_voltage;
        wire->max_current = p_max_current;
        wire->resistivity = p_resistivity;
        Rect2 rect(Vector2(p_p1.x, p_p1.z), Vector2());
        rect = rect.expand(Vector2(p_p2.x, p_p2.z));
        spatial_index->remove(p_wire);
        spatial_index->add(p_wire, rect.grow(5.0));
    }

    void TractionPowerServer::wire_free(const RID &p_wire) {
        spatial_index->remove(p_wire);
        wires.erase(p_wire);
    }

    void TractionPowerServer::network_build() {
        _resolve_power_sources();
        _connect_wires();
        _propagate_resistance();
    }

    void TractionPowerServer::_resolve_power_sources() {
        for (KeyValue<RID, Wire> &entry: wires) {
            Wire &wire = entry.value;
            if (wire.power_supply_name.is_empty() || wire.power_supply_name == "*" ||
                wire.power_supply_name == "none") {
                continue;
            }
            RID source_rid = power_source_get_rid_by_name(wire.power_supply_name);
            if (!source_rid.is_valid()) {
                UtilityFunctions::push_warning(
                        vformat(
                                "Bad scenario: traction piece connected to nonexistent power source \"%s\"",
                                wire.power_supply_name));
                source_rid = power_source_create();
                power_source_set_params(
                        source_rid, wire.power_supply_name, wire.nominal_voltage, 0.0, 0.2, wire.max_current, 1.0, 3,
                        60.0, false, true);
            }
            wire.power_source = source_rid;
            wire.power_near[0] = source_rid;
            wire.power_near[1] = source_rid;
            wire.resistance[0] = 0.0;
            wire.resistance[1] = 0.0;
        }
    }

    void TractionPowerServer::_connect_wires() {
        struct Endpoint {
                RID wire;
                int endpoint_index = 0;
                Vector3 position;
        };
        Vector<Endpoint> endpoints;
        for (const KeyValue<RID, Wire> &entry: wires) {
            endpoints.push_back({entry.key, 0, entry.value.p1});
            endpoints.push_back({entry.key, 1, entry.value.p2});
        }

        HashMap<Vector2i, Vector<int>> cells;
        for (int index = 0; index < endpoints.size(); ++index) {
            const Vector3 &position = endpoints[index].position;
            const Vector2i cell(
                    static_cast<int32_t>(Math::floor(position.x / ENDPOINT_EPSILON)),
                    static_cast<int32_t>(Math::floor(position.z / ENDPOINT_EPSILON)));
            cells[cell].push_back(index);
        }

        for (int i = 0; i < endpoints.size(); ++i) {
            const Endpoint &ep1 = endpoints[i];
            Wire *wire1 = wires.getptr(ep1.wire);
            if (wire1 == nullptr || wire1->next[ep1.endpoint_index].is_valid()) {
                continue;
            }
            const Vector2i cell(
                    static_cast<int32_t>(Math::floor(ep1.position.x / ENDPOINT_EPSILON)),
                    static_cast<int32_t>(Math::floor(ep1.position.z / ENDPOINT_EPSILON)));
            int best_index = -1;
            double best_distance = ENDPOINT_EPSILON;
            for (int dx = -1; dx <= 1; ++dx) {
                for (int dz = -1; dz <= 1; ++dz) {
                    const Vector<int> *bucket = cells.getptr(cell + Vector2i(dx, dz));
                    if (bucket == nullptr) {
                        continue;
                    }
                    for (int j: *bucket) {
                        if (j == i || endpoints[j].wire == ep1.wire) {
                            continue;
                        }
                        const Wire *wire2 = wires.getptr(endpoints[j].wire);
                        if (wire2 == nullptr || wire2->next[endpoints[j].endpoint_index].is_valid()) {
                            continue;
                        }
                        const double distance = ep1.position.distance_to(endpoints[j].position);
                        if (distance <= best_distance) {
                            best_distance = distance;
                            best_index = j;
                        }
                    }
                }
            }
            if (best_index < 0) {
                continue;
            }
            const Endpoint &ep2 = endpoints[best_index];
            Wire *wire2 = wires.getptr(ep2.wire);
            wire1->next[ep1.endpoint_index] = ep2.wire;
            wire1->next_endpoint[ep1.endpoint_index] = ep2.endpoint_index;
            wire2->next[ep2.endpoint_index] = ep1.wire;
            wire2->next_endpoint[ep2.endpoint_index] = ep1.endpoint_index;
        }
    }

    /* Port of TTraction::ResistanceCalc(), walking outward from every directly powered wire along
     * the hvNext chain in both directions, until it reaches a wire a nearer source already took. */
    void TractionPowerServer::_propagate_resistance() {
        Vector<RID> powered;
        for (const KeyValue<RID, Wire> &entry: wires) {
            if (entry.value.power_source.is_valid()) {
                powered.push_back(entry.key);
            }
        }
        for (const RID &wire_rid: powered) {
            const Wire *wire = wires.getptr(wire_rid);
            const double half_resistance = 0.5 * wire->resistivity * wire->length();
            _resistance_walk(wire_rid, 0, half_resistance, wire->power_source);
            _resistance_walk(wire_rid, 1, half_resistance, wire->power_source);
        }
    }

    void TractionPowerServer::_resistance_walk(
            const RID &p_from_wire, const int p_direction, const double p_resistance, const RID &p_source) {
        RID current_wire_rid = p_from_wire;
        int current_direction = p_direction;
        double current_resistance = p_resistance;
        while (true) {
            const Wire *current_wire = wires.getptr(current_wire_rid);
            if (current_wire == nullptr) {
                return;
            }
            const RID next_rid = current_wire->next[current_direction];
            if (!next_rid.is_valid()) {
                return;
            }
            Wire *next_wire = wires.getptr(next_rid);
            const int next_direction = current_wire->next_endpoint[current_direction];
            if (next_wire == nullptr || next_direction < 0 || next_wire->power_near[next_direction].is_valid()) {
                return;
            }
            next_wire->power_near[next_direction] = p_source;
            next_wire->resistance[next_direction] = current_resistance;
            current_resistance += next_wire->resistivity * next_wire->length();
            current_wire_rid = next_rid;
            current_direction = next_direction ^ 1;
        }
    }

    double TractionPowerServer::wire_get_voltage(
            const RID &p_wire, const double p_assumed_voltage, const double p_current) {
        const Wire *wire = wires.getptr(p_wire);
        if (wire == nullptr) {
            return 0.0;
        }
        /* A wire fed through the network rather than directly returns its nominal voltage here.
         * That is what the GDScript this ports did too - its star-network branch (power_near and
         * the two resistances) sat below this same early return and could never be reached, since
         * power_source is set only on directly powered wires. Ported as it behaved, not as it
         * read; see TODO.md. */
        if (!wire->power_source.is_valid()) {
            return wire->nominal_voltage;
        }
        const double res = !Math::is_zero_approx(p_current) ? p_assumed_voltage / p_current : 10000.0;

        // directly powered - take it straight from the source rather than through the star network
        PowerSource *direct_source = power_sources.getptr(wire->power_source);
        if (direct_source != nullptr && !Math::is_zero_approx(res)) {
            return direct_source->current_get(res) * res;
        }
        return 0.0;
    }

    Dictionary TractionPowerServer::wire_find_above_with_height(
            const Vector3 &p_position, const Vector3 &p_up, const Vector3 &p_forward, const Vector3 &p_left,
            const double p_width, const double p_horn_width) const {
        const Vector2 query_center(p_position.x, p_position.z);
        const Rect2 query_aabb(
                query_center - (Vector2(1.0, 1.0) * QUERY_MARGIN), Vector2(1.0, 1.0) * QUERY_MARGIN * 2.0);
        RID best_rid;
        double best_height = INFINITY;
        const TypedArray<RID> candidates = spatial_index->query(query_aabb);
        for (int index = 0; index < candidates.size(); ++index) {
            const RID wire_rid = candidates[index];
            const Wire *wire = wires.getptr(wire_rid);
            if (wire == nullptr) {
                continue;
            }
            const double vertical =
                    _wire_height_above(*wire, p_position, p_up, p_forward, p_left, p_width, p_horn_width);
            if (vertical < best_height) {
                best_height = vertical;
                best_rid = wire_rid;
            }
        }
        Dictionary result;
        result["rid"] = best_rid;
        result["height"] = best_height;
        return result;
    }

    Dictionary TractionPowerServer::wire_follow_above(
            const RID &p_from_wire, const Vector3 &p_position, const Vector3 &p_up, const Vector3 &p_forward,
            const Vector3 &p_left, const double p_width, const double p_horn_width) const {
        Dictionary result;
        result["rid"] = RID();
        result["height"] = INFINITY;

        RID wire_rid = p_from_wire;
        for (int hop = 0; hop < MAX_WIRE_HOPS; ++hop) {
            const Wire *wire = wires.getptr(wire_rid);
            if (wire == nullptr) {
                return result;
            }
            const Vector3 parametric = wire->p2 - wire->p1;
            const double front_dot = parametric.dot(p_forward);
            if (Math::is_zero_approx(front_dot)) {
                return result;
            }
            /* Which end the pantograph ran off decides which neighbour it ran onto - the two
             * ends of a span are hvNext[0] and hvNext[1] of the original's own list. */
            const double t = -(wire->p1.dot(p_forward) - p_position.dot(p_forward)) / front_dot;
            const double t_tolerance = ENDPOINT_EPSILON / Math::abs(front_dot);
            if (t < -t_tolerance) {
                wire_rid = wire->next[0];
                continue;
            }
            if (t > 1.0 + t_tolerance) {
                wire_rid = wire->next[1];
                continue;
            }
            const double vertical =
                    _wire_height_above(*wire, p_position, p_up, p_forward, p_left, p_width, p_horn_width);
            if (!Math::is_finite(vertical)) {
                /* Under the span but out of the collector's reach sideways. The original gives up
                 * on the chain here too and searches the area, because a parallel span it cannot
                 * see from this one may be the wire actually overhead (DynObj.cpp:8791). */
                return result;
            }
            result["rid"] = wire_rid;
            result["height"] = vertical;
            return result;
        }
        return result;
    }

    double TractionPowerServer::_wire_height_above(
            const Wire &p_wire, const Vector3 &p_position, const Vector3 &p_up, const Vector3 &p_forward,
            const Vector3 &p_left, const double p_width, const double p_horn_width) const {
        const Vector3 parametric = p_wire.p2 - p_wire.p1;
        const double front_dot = parametric.dot(p_forward);
        if (Math::is_zero_approx(front_dot)) {
            return INFINITY;
        }
        const double t = -(p_wire.p1.dot(p_forward) - p_position.dot(p_forward)) / front_dot;
        /* An absolute tolerance at each span's own ends, not a fraction of its length: a fraction
         * shrinks to a couple of centimetres of real overlap on a typical 20 m span, tighter than
         * the gap hand-authored scenery regularly leaves between adjacent pieces. Confirmed live -
         * a test caught EP07-424 crossing td.scn losing pantograph voltage for a frame at one
         * fixed point, which the Mover's NoVoltRelay then correctly read as a real loss of
         * contact. ENDPOINT_EPSILON is this file's own "close enough to be one wire" distance. */
        const double t_tolerance = ENDPOINT_EPSILON / Math::abs(front_dot);
        if (t < -t_tolerance || t > 1.0 + t_tolerance) {
            return INFINITY;
        }
        const Vector3 contact_point = p_wire.p1 + (parametric * static_cast<real_t>(t));
        const Vector3 to_contact = contact_point - p_position;
        const double vertical = to_contact.dot(p_up);
        if (vertical < 0.0) {
            return INFINITY;
        }
        /* Beyond the slider the wire is not lost: it runs onto the horn, which leads it back
         * (scene.cpp:105-112). A wire over the horn is counted as geometrically higher, rising to
         * HORN_CONTACT_RISE at the horn's tip, so a span properly overhead still wins against it. */
        const double lateral = Math::abs(to_contact.dot(p_left)) - p_width;
        if (lateral <= 0.0) {
            return vertical;
        }
        if (lateral >= p_horn_width) {
            return INFINITY;
        }
        return vertical + (HORN_CONTACT_RISE * lateral / p_horn_width);
    }
} // namespace godot
