{
  description = "MaSzyna API wrapper - double-precision GDExtension toolchain";

  # Pinned to the revision this was developed against, which carries Godot 4.7.2-stable.
  # GODOT_VERSION in the Makefile has to agree with godot-double's version, since the export
  # looks its template up by that version.
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/e554fab72f81915600f3f449b786fd9af40439a5";

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems =
        f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});
    in
    {
      packages = forAllSystems (
        pkgs:
        let
          inherit (pkgs) lib;

          # The engine the extension is built against. A single-precision Godot cannot load a
          # double-precision extension at all - it dies with a glibc heap assertion part way
          # through module initialisation - so every Godot that touches this project is this one.
          # Not in the binary cache: precision=double is not a variant Hydra builds.
          godot-editor = pkgs.godot.override { withPrecision = "double"; };
        in
        rec {
          # Exposed as `godot-double` rather than `godot`, which is both the name CMakeLists.txt
          # looks for first (FIND_PROGRAM NAMES godot-double godot) and the Makefile's GODOT
          # default. Naming it `godot` would silently shadow a single-precision editor already on
          # PATH, and the failure that follows looks like memory corruption rather than a mix-up.
          godot-double = pkgs.runCommand "godot-double-${godot-editor.version}" {
            meta = godot-editor.meta // {
              mainProgram = "godot-double";
              description = "${godot-editor.meta.description} (double precision)";
            };
            passthru = { inherit godot-editor; };
          } ''
            mkdir -p "$out/bin"
            ln -s ${lib.getExe godot-editor} "$out/bin/godot-double"
          '';

          # godot-cpp ships a single-precision extension_api.json only, and its
          # binding_generator.py refuses outright to generate double bindings from it:
          #   "Cannot do a precision=double build using '...' which was generated by Godot
          #    built with precision=single"
          # CMakeLists.txt dumps the double one on demand from whatever Godot it can find. This
          # is that dump as a derivation, so the result is shared and pinned instead of being
          # rebuilt per checkout. Drop it in as ./extension_api.json and the CMake dump path
          # never runs - GODOTCPP_CUSTOM_API_FILE is set with CACHE ... FORCE and so cannot be
          # pointed elsewhere from the command line.
          extension-api-double =
            pkgs.runCommand "extension_api-${godot-editor.version}-double.json"
              {
                nativeBuildInputs = [ godot-double ];
                meta.description = "Double-precision GDExtension API description for godot-cpp";
              }
              ''
                export HOME="$TMPDIR"
                export XDG_DATA_HOME="$TMPDIR/share"
                export XDG_CONFIG_HOME="$TMPDIR/config"
                cd "$TMPDIR"

                # --dump-extension-api writes extension_api.json into the working directory
                godot-double --headless --dump-extension-api

                # The same check CMakeLists.txt makes, so a wrong engine fails here and not
                # thousands of template errors deep into the binding build.
                grep -q '"precision": "double"' extension_api.json \
                  || { echo "godot-double did not dump a double-precision API" >&2; exit 1; }

                cp extension_api.json "$out"
              '';

          default = godot-double;
        }
      );

      devShells = forAllSystems (pkgs: {
        default = pkgs.mkShell {
          name = "maszyna-api-wrapper";

          packages = [
            # The build itself
            pkgs.cmake
            pkgs.ninja
            pkgs.python3
            pkgs.scons

            # scripts/style-check drives clang-format and clang-tidy, and configures its own
            # build dir with -DCMAKE_CXX_COMPILER=clang++, so the compiler is needed too.
            # Pinned to LLVM 22 to match LLVM_VERSION in .github/workflows/clang-tidy.yml:
            # clang-format reformats differently between major versions, so a shell on a
            # different major reports violations CI does not, and misses ones it does.
            pkgs.llvmPackages_22.clang-tools
            pkgs.llvmPackages_22.clang

            # make compile-windows-{debug,release} call x86_64-w64-mingw32-g++ by name
            pkgs.pkgsCross.mingwW64.buildPackages.gcc

            self.packages.${pkgs.stdenv.hostPlatform.system}.godot-double
          ];

          shellHook = ''
            # CMakeLists.txt dumps this on first configure if it is absent, which needs
            # godot-double to start up. Linking the pinned derivation instead keeps the first
            # configure quick and makes every checkout agree on the file.
            # -f, because a symlink left by an earlier shell whose store path has since been
            # garbage collected is dangling: it fails [ -e ] but still occupies the name.
            if [ -f CMakeLists.txt ] && [ ! -e extension_api.json ]; then
              ln -sfn ${self.packages.${pkgs.stdenv.hostPlatform.system}.extension-api-double} \
                extension_api.json
              echo "linked extension_api.json (double precision)"
            fi
          '';
        };
      });
    };
}
