FROM ubuntu:latest
ENV ANDROID_SDK_ROOT=/root/sdk
ENV PROJECT_DIR=/var/maszyna
ENV ANDROID_NDK_VERSION=23.2.8568313
ENV ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/${ANDROID_NDK_VERSION}
ENV OSX_SDK_VERSION=14.5
ENV OSXCROSS_ROOT=/root/osxcross
ENV PATH="${OSXCROSS_ROOT}/target/bin:${PATH}"
LABEL authors="DoS"
RUN apt update
RUN apt upgrade -y
RUN apt install -y scons g++-mingw-w64-x86-64 gcc-mingw-w64 git-all build-essential cmake gcc-multilib g++-multilib libc6-dev-i386 g++-mingw-w64-i686
RUN apt install -y openjdk-17-jdk openjdk-17-jre libncurses5-dev libncursesw5-dev curl unzip zip libssl-dev lzma-dev libxml2-dev zlib1g-dev
RUN echo "Installing Android SDK..."
RUN mkdir -p ${ANDROID_SDK_ROOT} && cd ${ANDROID_SDK_ROOT}
RUN export CMDLINETOOLS=commandlinetools-linux-11076708_latest.zip && \
        curl -LO https://dl.google.com/android/repository/${CMDLINETOOLS} && \
        unzip ${CMDLINETOOLS} && \
        rm ${CMDLINETOOLS} && \
        yes | cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses && \
        cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "ndk;${ANDROID_NDK_VERSION}" 'cmdline-tools;latest' 'build-tools;34.0.0' 'platforms;android-34' 'cmake;3.22.1'

RUN apt install -y --no-install-recommends \
    ca-certificates \
    git \
    git-lfs \
    wget \
    adb \
    openjdk-17-jdk-headless \
    rsync \
    wine64 \
    osslsigncode \
    && rm -rf /var/lib/apt/lists/*

# When in doubt, see the downloads page: https://downloads.tuxfamily.org/godotengine/
ARG GODOT_VERSION="4.3"
ARG RELEASE_NAME="stable"
ARG GODOT_TEST_ARGS=""
ARG GODOT_PLATFORM="linux.x86_64"

RUN wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-${RELEASE_NAME}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM}.zip \
    && wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-${RELEASE_NAME}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz \
    && mkdir ~/.cache \
    && mkdir -p ~/.config/godot \
    && mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME} \
    && unzip Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM}.zip \
    && mv Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM} /usr/local/bin/godot \
    && unzip Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz \
    && mv templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME} \
    && rm -f Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz Godot_v${GODOT_VERSION}-${RELEASE_NAME}_${GODOT_PLATFORM}.zip