name: "Bug Report"
description: Create a new ticket for a bug.
labels: [
  "bug"
]
body:
  - type: dropdown
    id: os
    attributes:
      label: "Platform"
      description: Affected platforms / operating systems
      multiple: true
      options:
        - Windows 64bit
        - Windows 32bit
        - Linux 64bit
        - Linux 32bit
        - Android 64bit/armv8
        - Android 32bit/armv7
        - Other (provide info in a description)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots and attachments"
      description: If applicable, add screenshots or attachments to help explain your problem.
    validations:
      required: false
