name: "Feature Request"
description: Create a new ticket for a new feature request
labels: [
  "enhancement"
]
body:
  - type: textarea
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: full_descrtiption
    attributes:
      label: "Full description"
      placeholder: Describe the feature. Add mockups or attachments if needed.
    validations:
      required: true
