@tool
extends Node

## Electrical topology for overhead traction wires - kept separate from
## TractionRenderingServer (meshes only) per this codebase's separation of
## concerns between rendering and simulation servers (see TrackManager vs.
## TrackRenderingServer). Ports Traction.cpp/TractionPower.cpp from the
## original MaSzyna engine (~/src/maszyna): named power sources feeding wire
## spans, a resistive network built once per scenery load
## (traction_table::InitTraction()), and the geometric "which wire is above
## this point" query (scene::basic_cell::update_traction()).
##
## Not ported: TTraction::PowerSet()'s section-marker replacement dance
## (Traction.cpp:747-806, relevant only when a sectioning cabin sits between
## two differently-named substations) and update_traction()'s "nabieżnik"
## (pantograph horn) lateral tolerance correction - both are edge-case
## refinements on top of the core network/contact logic ported here, not
## required for a wire to deliver the right voltage to a pantograph.

const _ENDPOINT_EPSILON:float = 0.25
const _GRID_CELL_SIZE:float = 500.0
const _QUERY_MARGIN:float = 10.0


class PowerSourceState:
    var name:String = ""
    var nominal_voltage:float = 0.0
    var voltage_frequency:float = 0.0
    var internal_resistance:float = 0.2
    var max_output_current:float = 0.0
    var fast_fuse_timeout:float = 1.0
    var fast_fuse_repetition:float = 3
    var slow_fuse_timeout:float = 60.0
    var recuperation:bool = false
    var is_autogenerated:bool = false

    # runtime state - mirrors TractionPowerSource's own members
    var total_current:float = 0.0
    var total_admittance:float = 1e-10
    var total_previous_admittance:float = 1e-10
    var output_voltage:float = 0.0
    var fast_fuse:bool = false
    var slow_fuse:bool = false
    var fuse_timer:float = 0.0
    var fuse_counter:int = 0

    func fuse() -> bool:
        return fast_fuse or slow_fuse

    ## Port of TTractionPowerSource::Update(dt) - called once per physics step.
    func tick(delta:float) -> void:
        if fast_fuse or slow_fuse:
            total_current = 0.0
        if total_current > max_output_current:
            fast_fuse = true
            fuse_counter += 1
            if fuse_counter > fast_fuse_repetition:
                slow_fuse = true
                push_warning("Power overload: \"%s\" disabled for %ss" % [name, slow_fuse_timeout])
            else:
                push_warning("Power overload: \"%s\" disabled for %ss" % [name, fast_fuse_timeout])
            fuse_timer = 0.0
        if fast_fuse or slow_fuse:
            total_admittance = 0.0
            fuse_timer += delta
            if not slow_fuse:
                if fuse_timer > fast_fuse_timeout:
                    fast_fuse = false
            elif fuse_timer > slow_fuse_timeout:
                slow_fuse = false
                fuse_counter = 0
        total_previous_admittance = total_admittance
        if is_zero_approx(total_previous_admittance):
            total_previous_admittance = 1e-10
        total_admittance = 1e-10

    ## Port of TTractionPowerSource::CurrentGet(res) - current proportional to
    ## this resistance's share of the source's total admittance.
    func current_get(res:float) -> float:
        if fast_fuse or slow_fuse:
            if res < 100.0:
                fuse_timer = 0.0
            return 0.0
        if not is_zero_approx(res):
            total_admittance += 1.0 / res
        var nominal:float = nominal_voltage * 1.083 if total_previous_admittance < 0.0 else nominal_voltage
        total_current = (
            nominal / (internal_resistance + 1.0 / total_previous_admittance)
            if not is_zero_approx(total_previous_admittance)
            else 0.0
        )
        output_voltage = nominal - internal_resistance * total_current
        return total_current / (res * total_previous_admittance)


class WireState:
    var p1:Vector3 = Vector3.ZERO
    var p2:Vector3 = Vector3.ZERO
    var power_supply_name:String = ""
    var nominal_voltage:float = 0.0
    var max_current:float = 0.0
    var resistivity:float = 0.0

    var power_source:RID = RID() # psPowered - directly powered (short-circuit) wire
    var power_near:Array = [RID(), RID()] # psPower[0], psPower[1]
    var resistance:Array = [-1.0, -1.0] # fResistance[0], fResistance[1]
    var next:Array = [RID(), RID()] # hvNext[0], hvNext[1]
    var next_endpoint:Array = [-1, -1] # iNext[0], iNext[1]

    func length() -> float:
        return p1.distance_to(p2)


var _power_sources:Dictionary[RID, PowerSourceState] = {}
var _power_sources_by_name:Dictionary[String, RID] = {}
var _next_power_source_id:int = 0

var _wires:Dictionary[RID, WireState] = {}
var _next_wire_id:int = 0
var _spatial_index:SpatialIndex = SpatialIndex.new(_GRID_CELL_SIZE)


func _physics_process(delta:float) -> void:
    for source:PowerSourceState in _power_sources.values():
        source.tick(delta)


func power_source_create() -> RID:
    _next_power_source_id += 1
    var rid:RID = rid_from_int64(_next_power_source_id)
    _power_sources[rid] = PowerSourceState.new()
    return rid


func power_source_set_params(
    power_source_rid:RID,
    name:String,
    nominal_voltage:float,
    voltage_frequency:float,
    internal_resistance:float,
    max_output_current:float,
    fast_fuse_timeout:float,
    fast_fuse_repetition:int,
    slow_fuse_timeout:float,
    recuperation:bool,
    is_autogenerated:bool = false
) -> void:
    var source:PowerSourceState = _power_sources.get(power_source_rid)
    if not source:
        return
    source.name = name
    source.nominal_voltage = nominal_voltage
    source.voltage_frequency = voltage_frequency
    source.internal_resistance = internal_resistance
    source.max_output_current = max_output_current
    source.fast_fuse_timeout = fast_fuse_timeout
    source.fast_fuse_repetition = fast_fuse_repetition
    source.slow_fuse_timeout = slow_fuse_timeout
    source.recuperation = recuperation
    source.is_autogenerated = is_autogenerated
    if not name.is_empty():
        _power_sources_by_name[name] = power_source_rid


func power_source_get_rid_by_name(name:String) -> RID:
    return _power_sources_by_name.get(name, RID())


func power_source_free(power_source_rid:RID) -> void:
    var source:PowerSourceState = _power_sources.get(power_source_rid)
    if source and _power_sources_by_name.get(source.name) == power_source_rid:
        _power_sources_by_name.erase(source.name)
    _power_sources.erase(power_source_rid)


func wire_create() -> RID:
    _next_wire_id += 1
    var rid:RID = rid_from_int64(_next_wire_id)
    _wires[rid] = WireState.new()
    return rid


func wire_set_params(
    wire_rid:RID,
    p1:Vector3,
    p2:Vector3,
    power_supply_name:String,
    nominal_voltage:float,
    max_current:float,
    resistivity:float
) -> void:
    var wire:WireState = _wires.get(wire_rid)
    if not wire:
        return
    wire.p1 = p1
    wire.p2 = p2
    wire.power_supply_name = power_supply_name
    wire.nominal_voltage = nominal_voltage
    wire.max_current = max_current
    wire.resistivity = resistivity
    var rect:Rect2 = Rect2(Vector2(p1.x, p1.z), Vector2.ZERO).expand(Vector2(p2.x, p2.z))
    _spatial_index.remove(wire_rid)
    _spatial_index.add(wire_rid, rect.grow(5.0))


func wire_free(wire_rid:RID) -> void:
    _spatial_index.remove(wire_rid)
    _wires.erase(wire_rid)


## Resolves named power sources (auto-creating one from a wire's own nominal
## voltage/current when the name doesn't match any registered source - port
## of traction_table::InitTraction()'s fallback, Traction.cpp:704-721),
## connects wire endpoints into a network, and propagates source/resistance
## outward from every directly-powered wire. Call once per scenery load,
## after every wire_create()/power_source_create() for that load is done.
func network_build() -> void:
    _resolve_power_sources()
    _connect_wires()
    _propagate_resistance()


func _resolve_power_sources() -> void:
    for wire:WireState in _wires.values():
        if wire.power_supply_name.is_empty() or wire.power_supply_name == "*" or wire.power_supply_name == "none":
            continue
        var source_rid:RID = power_source_get_rid_by_name(wire.power_supply_name)
        if not source_rid.is_valid():
            push_warning(
                "Bad scenario: traction piece connected to nonexistent power source \"%s\""
                % wire.power_supply_name
            )
            source_rid = power_source_create()
            power_source_set_params(
                source_rid, wire.power_supply_name, wire.nominal_voltage, 0.0, 0.2,
                wire.max_current, 1.0, 3, 60.0, false, true
            )
        wire.power_source = source_rid
        wire.power_near = [source_rid, source_rid]
        wire.resistance = [0.0, 0.0]


func _connect_wires() -> void:
    var endpoints:Array[Dictionary] = []
    for wire_rid:RID in _wires:
        var wire:WireState = _wires[wire_rid]
        endpoints.append({"wire_rid": wire_rid, "endpoint_index": 0, "position": wire.p1})
        endpoints.append({"wire_rid": wire_rid, "endpoint_index": 1, "position": wire.p2})

    var cells:Dictionary = {}
    for index:int in endpoints.size():
        var cell:Vector2i = _endpoint_cell(endpoints[index]["position"])
        if not cells.has(cell):
            cells[cell] = []
        cells[cell].append(index)

    for i:int in endpoints.size():
        var ep1:Dictionary = endpoints[i]
        var wire1:WireState = _wires[ep1["wire_rid"]]
        if wire1.next[ep1["endpoint_index"]].is_valid():
            continue

        var cell:Vector2i = _endpoint_cell(ep1["position"])
        var best_index:int = -1
        var best_distance:float = _ENDPOINT_EPSILON
        for dx:int in range(-1, 2):
            for dz:int in range(-1, 2):
                for j:int in cells.get(cell + Vector2i(dx, dz), []):
                    if j == i:
                        continue
                    var ep2:Dictionary = endpoints[j]
                    if ep2["wire_rid"] == ep1["wire_rid"]:
                        continue
                    var wire2:WireState = _wires[ep2["wire_rid"]]
                    if wire2.next[ep2["endpoint_index"]].is_valid():
                        continue
                    var distance:float = (ep1["position"] as Vector3).distance_to(ep2["position"])
                    if distance <= best_distance:
                        best_distance = distance
                        best_index = j

        if best_index < 0:
            continue
        var ep2:Dictionary = endpoints[best_index]
        var wire2:WireState = _wires[ep2["wire_rid"]]
        wire1.next[ep1["endpoint_index"]] = ep2["wire_rid"]
        wire1.next_endpoint[ep1["endpoint_index"]] = ep2["endpoint_index"]
        wire2.next[ep2["endpoint_index"]] = ep1["wire_rid"]
        wire2.next_endpoint[ep2["endpoint_index"]] = ep1["endpoint_index"]


func _endpoint_cell(position:Vector3) -> Vector2i:
    return Vector2i(floori(position.x / _ENDPOINT_EPSILON), floori(position.z / _ENDPOINT_EPSILON))


## Port of TTraction::ResistanceCalc(), walking outward from every directly
## powered wire along the hvNext-equivalent chain in both directions, until
## hitting a wire a nearer source already claimed.
func _propagate_resistance() -> void:
    for wire_rid:RID in _wires:
        var wire:WireState = _wires[wire_rid]
        if not wire.power_source.is_valid():
            continue
        var half_resistance:float = 0.5 * wire.resistivity * wire.length()
        _resistance_walk(wire_rid, 0, half_resistance, wire.power_source)
        _resistance_walk(wire_rid, 1, half_resistance, wire.power_source)


func _resistance_walk(from_wire_rid:RID, direction:int, resistance:float, source_rid:RID) -> void:
    var current_wire_rid:RID = from_wire_rid
    var current_direction:int = direction
    var current_resistance:float = resistance
    while true:
        var current_wire:WireState = _wires[current_wire_rid]
        var next_rid:RID = current_wire.next[current_direction]
        if not next_rid.is_valid():
            return
        var next_wire:WireState = _wires[next_rid]
        var next_direction:int = current_wire.next_endpoint[current_direction]
        if next_wire.power_near[next_direction].is_valid():
            return
        next_wire.power_near[next_direction] = source_rid
        next_wire.resistance[next_direction] = current_resistance
        current_resistance += next_wire.resistivity * next_wire.length()
        current_wire_rid = next_rid
        current_direction = next_direction ^ 1


## Port of TTraction::VoltageGet(u, i). `assumed_voltage` is the vehicle's own
## previous-frame voltage reading (used only to derive an equivalent load
## resistance, same relaxation trick the original uses), `current` the actual
## instantaneous draw.
func wire_get_voltage(wire_rid:RID, assumed_voltage:float, current:float) -> float:
    var wire:WireState = _wires.get(wire_rid)
    if not wire:
        return 0.0
    if not wire.power_source.is_valid():
        return wire.nominal_voltage

    var res:float = (assumed_voltage / current) if not is_zero_approx(current) else 10000.0

    if wire.power_source.is_valid():
        # directly powered - don't bother with the star network, take it straight from the source
        var direct_source:PowerSourceState = _power_sources.get(wire.power_source)
        return direct_source.current_get(res) * res if not is_zero_approx(res) and direct_source else 0.0

    var source0:PowerSourceState = _power_sources.get(wire.power_near[0])
    var source1:PowerSourceState = _power_sources.get(wire.power_near[1])
    if (source0 and source0.fuse()) or (source1 and source1.fuse()):
        return 0.0

    var r0t:float = wire.resistance[0]
    var r1t:float = wire.resistance[1]
    if source0 and source1:
        if r0t > 0.0 and r1t > 0.0:
            var r0g:float = res + r0t + (res * r0t) / r1t
            var r1g:float = res + r1t + (res * r1t) / r0t
            var i0:float = source0.current_get(r0g)
            var i1:float = source1.current_get(r1g)
            return (i0 + i1) * res
        elif r0t >= 0.0:
            return source0.current_get(res + r0t) * res
        elif r1t >= 0.0:
            return source1.current_get(res + r1t) * res
        return 0.0
    elif source0 and r0t >= 0.0:
        return source0.current_get(res + r0t) * res
    elif source1 and r1t >= 0.0:
        return source1.current_get(res + r1t) * res
    return 0.0


## Port of scene::basic_cell::update_traction()'s geometry test: which wire
## span (if any) passes above `position` within the collector's `width`,
## along the plane swept by the pantograph as the vehicle moves in `forward`.
func wires_find_above(position:Vector3, up:Vector3, forward:Vector3, left:Vector3, width:float) -> RID:
    var query_center:Vector2 = Vector2(position.x, position.z)
    var query_aabb:Rect2 = Rect2(query_center - Vector2.ONE * _QUERY_MARGIN, Vector2.ONE * _QUERY_MARGIN * 2.0)
    var best_rid:RID = RID()
    var best_height:float = INF
    for wire_rid:RID in _spatial_index.query(query_aabb):
        var wire:WireState = _wires.get(wire_rid)
        if not wire:
            continue
        var parametric:Vector3 = wire.p2 - wire.p1
        var front_dot:float = parametric.dot(forward)
        if is_zero_approx(front_dot):
            continue
        var t:float = -(wire.p1.dot(forward) - position.dot(forward)) / front_dot
        # Absolute-distance tolerance at each segment's own endpoints, not a fixed fraction of
        # its length - a fraction (the previous 0.001 here) shrinks to a couple centimeters of
        # real overlap for a typical ~20m span, tighter than the gap hand-authored scenery
        # regularly leaves between adjacent traction pieces (confirmed live: a GUT test caught
        # EP07-424 crossing td.scn get a real, reproducible single-to-few-frame
        # pantograph_first_voltage=0.0 at one fixed point on the track, which Mover's own
        # NoVoltRelay logic then correctly read as a genuine loss of contact and tripped Mains -
        # not a Mover bug, a real gap in wire coverage at that exact seam). _ENDPOINT_EPSILON is
        # this same file's own established "close enough to be one continuous wire" distance,
        # already used for the electrical connectivity graph in _connect_wires() below.
        var t_tolerance:float = _ENDPOINT_EPSILON / absf(front_dot)
        if t < -t_tolerance or t > 1.0 + t_tolerance:
            continue
        var contact_point:Vector3 = wire.p1 + parametric * t
        var to_contact:Vector3 = contact_point - position
        var vertical:float = to_contact.dot(up)
        if vertical < 0.0:
            continue
        var horizontal:float = absf(to_contact.dot(left)) - width
        if horizontal > 0.0:
            continue
        if vertical < best_height:
            best_height = vertical
            best_rid = wire_rid
    return best_rid
