#include "VehicleComponentType.hpp"

namespace godot {
    void VehicleComponentType::_bind_methods() {
        BIND_ENUM_CONSTANT(COMPONENT_NONE);
        BIND_ENUM_CONSTANT(COMPONENT_BRAKES);
        BIND_ENUM_CONSTANT(COMPONENT_SPRING_BRAKE);
        BIND_ENUM_CONSTANT(COMPONENT_EP_ED_BRAKE);
        BIND_ENUM_CONSTANT(COMPONENT_BUFFERS);
        BIND_ENUM_CONSTANT(COMPONENT_DOORS);
        BIND_ENUM_CONSTANT(COMPONENT_ENGINE);
        BIND_ENUM_CONSTANT(COMPONENT_HEATING);
        BIND_ENUM_CONSTANT(COMPONENT_LIGHTING);
        BIND_ENUM_CONSTANT(COMPONENT_LOAD);
        BIND_ENUM_CONSTANT(COMPONENT_SPEED_CONTROL);
        BIND_ENUM_CONSTANT(COMPONENT_SWITCHES);
        BIND_ENUM_CONSTANT(COMPONENT_AI_HINTS);
        BIND_ENUM_CONSTANT(COMPONENT_HORNS);
        BIND_ENUM_CONSTANT(COMPONENT_SECURITY);
        BIND_ENUM_CONSTANT(COMPONENT_WHEELS);
        BIND_ENUM_CONSTANT(COMPONENT_WIPERS);
        BIND_ENUM_CONSTANT(COMPONENT_UNIVERSAL_CONTROLLER);
        BIND_ENUM_CONSTANT(COMPONENT_GENERIC);
    }
} // namespace godot
