title: MaSzyna Reloaded Core

description: >- # this means to ignore newlines until "baseurl:"
  MaSzyna: Reloaded is a development organization dedicated to creating
  a next-generation train simulator based on https://eu07.pl experience
  built with the Godot Engine.

github_username: MaSzyna-Reloaded

baseurl: /MaSzyna-API-wrapper
theme: minima

header_pages:
  - architecture.markdown
  - wrapping-mover.md
