name: docker-build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        arch: [x86_64]
        target: [template_debug]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - uses: actions/cache/restore@v4.2.3
        id: cache-restore
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ matrix.target }}-windows-${{ matrix.arch }}-godot-cpp
          restore-keys: |
            ${{ matrix.target }}-windows-${{ matrix.arch }}-godot-
            ${{ matrix.target }}-windows-${{ matrix.arch }}

      - name: Docker build Windows ${{ matrix.arch }}
        run: sudo chmod 777 ci/docker/entrypoint.sh |
          docker compose run windows_${{ matrix.arch }} ${{ matrix.target }}

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: lib-windows-${{ matrix.target }}-${{ matrix.arch }}
          path: bin/windows

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: game-windows-${{ matrix.target }}-${{ matrix.arch }}
          path: build/windows

      - uses: actions/cache/save@v4.2.3
        id: cache
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ matrix.target }}-windows-${{ matrix.arch }}-godot-cpp

  build-linux:
    strategy:
      matrix:
        arch: [x86_64]
        target: [template_debug]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - uses: actions/cache/restore@v4.2.3
        id: cache-restore
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ matrix.target }}-linux-${{ matrix.arch }}-godot-cpp
          restore-keys: |
            ${{ matrix.target }}-linux-${{ matrix.arch }}-godot-
            ${{ matrix.target }}-linux-${{ matrix.arch }}-

      - name: Docker build Linux ${{ matrix.arch }}
        run: sudo chmod 777 ci/docker/entrypoint.sh |
          docker compose run linux_${{ matrix.arch }} ${{ matrix.target }}

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: lib-linux-${{ matrix.target }}-${{ matrix.arch }}
          path: bin/linux

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: game-linux-${{ matrix.target }}-${{ matrix.arch }}
          path: build/linux

      - uses: actions/cache/save@v4.2.3
        id: cache
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ matrix.target }}-linux-${{ matrix.arch }}-godot-cpp

  build-android:
    strategy:
      matrix:
        arch: [x86_64, arm64]
        target: [template_debug]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - uses: actions/cache/restore@v4.2.3
        id: cache-restore
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ matrix.target }}-android-godot-cpp
          restore-keys: |
            ${{ matrix.target }}-android-${{ matrix.arch }}-godot-
            ${{ matrix.target }}-android-

      - name: Docker build Android ${{ matrix.arch }}
        run: sudo chmod 777 ci/docker/entrypoint.sh |
          docker compose run android_${{ matrix.arch }} ${{ matrix.target }}

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: lib-android-${{ matrix.target }}-${{ matrix.arch }}
          path: bin/android

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: game-android-${{ matrix.target }}-${{ matrix.arch }}
          path: build/android

      - uses: actions/cache/save@v4.2.3
        id: cache
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ matrix.target }}-android-${{ matrix.arch }}-godot-cpp