name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ZedThree/clang-tidy-review@v0.20.1
        id: review
        with:
          config_file: ".clang-tidy"
          include: "src/*"
          exclude: "src/maszyna/*,src/gen/*"

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.20.1
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
