name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Optionally generate compile_commands.json
      - name: Fix godot-cpp directory
        run: |
          cd ${{ github.workspace }}
          mkdir src/godot_cpp
          cp -r godot-cpp src/godot_cpp
      - uses: ZedThree/clang-tidy-review@v0.20.1
        id: review
        with:
          config_file: ".clang-tidy"
          exclude: "demo/"
          include: "godot-cpp/*, godot_cpp/*, *.[ch]pp, *.h, src/*"

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.14.0
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1