name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - "releases/*" # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v4  
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }} # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0 # a full history is required for pull request analysis
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: "Prepare Codebase"
        run: |
          sudo chmod +x ./ci/qodana/generate_cmakelists.sh
          cd ci/qodana/
          ./generate_cmakelists.sh
      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
          upload-result: true
          post-pr-comment: false
          args: --linter,jetbrains/qodana-cpp:2025.1-eap-clang18,--property=project.open.type=Maven
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: "https://qodana.cloud"
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          category: qodana
