name: Run Godot Tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: maszyna-reloaded/core
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        run: docker run --rm ${{ steps.meta.outputs.tags }}
