name: Run Godot Tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - uses: actions/cache/restore@v4.2.3
        id: cache-restore
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: godot-unit-tests
          restore-keys: |
            godot-unit-tests
            godot-unit-
      - name: Run tests
        run: sudo chmod 777 ci/docker/entrypoint.sh |
          docker compose run unit_tests
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: gut-test-results
          path: demo/test_results.xml
      - uses: actions/cache/save@v4.2.3
        id: cache
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: godot-unit-tests